version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'
  DC_FILE: "compose.yml"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [ format ]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  build_image:
    cmds:
      - "{{.MVNW}} clean protobuf:compile package spring-boot:build-image -DskipTests"

  start:
    deps: [ build_image ]
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" up --force-recreate -d

  stop:
    cmds:
      - docker compose --profile app -f "{{.DC_FILE}}" stop
      - docker compose --profile app -f "{{.DC_FILE}}" rm -f

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  kind_create:
    cmds:
      - ./k8s/kind/kind-cluster.sh create

  kind_destroy:
    cmds:
      - ./k8s/kind/kind-cluster.sh destroy

  k8s_deploy:
    cmds:
      - kind load docker-image sivaprasadreddy/spring-modular-monolith --name sivalabs-k8s
      - kubectl apply -f k8s/manifests/

  k8s_undeploy:
    cmds:
      - kubectl delete -f k8s/manifests/

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"
