apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
  namespace: orders
spec:
  selector:
    app: orders-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  labels:
    app: orders-service
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: philipz/orders-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          envFrom:
            - configMapRef:
                name: orders-service-config
            - secretRef:
                name: orders-service-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
