apiVersion: v1
kind: Service
metadata:
  name: orders-postgres
  labels:
    app: orders-postgres
  namespace: orders
spec:
  selector:
    app: orders-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-postgres
  labels:
    app: orders-postgres
  namespace: orders
spec:
  serviceName: orders-postgres
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ordersdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-service-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-service-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
