apiVersion: v1
kind: Secret
metadata:
  name: orders-service-secrets
  labels:
    app: orders-service
  namespace: orders
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: b3JkZXJz
  SPRING_DATASOURCE_PASSWORD: b3JkZXJz
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=
