apiVersion: v1
kind: Service
metadata:
  name: spring-modular-monolith-hazelcast-mgmt-svc
spec:
  type: NodePort
  selector:
    app: spring-modular-monolith-hazelcast-mgmt-pod
  ports:
    - name: hazelcast-mgmt-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-modular-monolith-hazelcast-mgmt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-modular-monolith-hazelcast-mgmt-pod
  template:
    metadata:
      labels:
        app: spring-modular-monolith-hazelcast-mgmt-pod
    spec:
      containers:
        - name: hazelcast-mgmt
          image: hazelcast/management-center:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: HZ_CLUSTERNAME
              value: "bookstore-cluster"
            - name: HZ_NETWORK_PORT_AUTOINCREMENT
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
