name: Maven Build

on:
  push:
    branches:
      - "main"
      - "package-by-*"
    paths-ignore:
      - '.gitignore'
      - '.sdkmanrc'
      - 'README.md'
      - 'LICENSE'
      - 'Taskfile.yml'
      - 'renovate.json'
      - 'k8s/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'pom.xml'
      - '**/pom.xml'
      - 'src/**'
      - '.github/workflows/maven.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for dependency submission
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v5